name: Tag and commit
description: Create a tag and commits changes to the git repository
inputs:
  is_release_candidate:
    description: true/false determining if this is a release candidate (new deploy) or not
    required: true
    default: 'true'
  commit_message:
    description: the commit message for any changes made by former actions
    required: true
  tag_message:
    description: the tag message for this release.
    required: true
  tag:
    description: the tag to use with git tag
    required: true
  pattern:
    description: the pattern to use with git add
    required: true
  new_snapshot_version:
    description: the value of the new SNAPSHOT-version to use after release of current project object model (pom.xml for maven), if given the tagged version vil be committed first
    required: false
runs:
  using: node12
  main: dist/index.js
