name: Verify auto deploy
description: Verifies that the new commit contains at least one section in the changelog file that contains the version that is to be released
inputs:
  changelog_file:
    description: the file containing the changelog for this release
    required: true
    default: README.md
  release_version_file:
    description: the file containing this release version
    required: true
    default: .release-version
runs:
  using: node12
  main: dist/index.js
