name: build actions
on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-16.04
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm i -g @zeit/ncc
      - name: Debug workspace
        run: env
      - name: Install mvn-github-pkg
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: bidrag-release/mvn-github-pkg
      - name: Install prepare-mvn-pkg
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: bidrag-release/prepare-mvn-pkg
      - name: Install tag-n-commit-release
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: bidrag-release/tag-n-commit-release
      - name: Install verify-auto-release
        uses: navikt/bidrag-node/build-with-ncc@v1
        with:
          artifact_folder: bidrag-release/verify-auto-release
      - name: Generate timestamp
        id: now
        run: echo ::set-output name=timestamp::$(date +"%Y-%m-%d:%T")
      - uses: navikt/bidrag-git/commit@v3.0.3
        with:
          commit_message: "${{ steps.now.outputs.timestamp }}: Build of actions with npm and ncc"
          pattern: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
